services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports: 
      - 3000:3000
    volumes:
      - ./frontend:/frontend

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - 4000:4000
    volumes:
      - ./backend:/backend
      - ./backend/database/database.sqlite:/backend/database/database.sqlite
